site_name: Njord protocol
theme:
  name: material
  features:
    - toc.integrate 
    - navigation.top
    - search.highlight
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.footer
    - navigation.footer
plugins:
  - search
  - offline
  - with-pdf
copyright: Copyright &copy; 2016 - 2020 Martin Donath
extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
nav:
 - Home: index.md
 - Introduction: introduction.md
 - Protocol:
    - Stakeholders: stakeholders.md
    - Protocol Flow: protocol_flow.md
 - Getting Started: getting_started.md
